steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--platform=linux/amd64', '-t', 'gcr.io/$PROJECT_ID/SERVICE_NAME:$COMMIT_SHA', '.']
  # Run tests
  - name: "gcr.io/cloud-builders/npm"
    args: ["test"]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/SERVICE_NAME:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'SERVICE_NAME'
      - '--image'
      - 'gcr.io/$PROJECT_ID/SERVICE_NAME:$COMMIT_SHA'
      - '--region'
      - 'SERVICE_REGION'
images:
  - 'gcr.io/$PROJECT_ID/SERVICE_NAME:$COMMIT_SHA'